services:
  - type: web
    name: education-website
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: true
